#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e ${RED}vagrant up${NC}
vagrant up
echo -e ${RED}vagrant provision${NC}
vagrant provision
echo -e ${RED}vagrant reload${NC}
vagrant reload
echo -e ${RED}vagrant ssh${NC}
vagrant ssh
